<div align="center">
    <h1> My Machine Learning Journey</h1>
Civl Engineer · Researcher Youtuber · Machine Learning Engineer (The Goal)
    <br>
    Sharing and documenting my progress and journey as I learn machine learning
     <br>
</div>

<br>

<div align="center">
    <a target="_blank" href="https://github.com/barbaraaboagye/My-MachineLearning-Journey"><img src="https://img.shields.io/github/last-commit/barbaraaboagye/My-MachineLearning-Journey"></a>&nbsp;
      <a target="_blank" href="https://www.youtube.com/channel/UCEYKFq7ZEg81GYxpzNqYZ4)"><img src="https://img.shields.io/youtube/channel/subscribers/UCEYKFq7ZEg81GYxpzNqYZ4Q?style=social"></a>&nbsp;
    <a target="_blank" href="https://fr.linkedin.com/in/barbara-aboagye-233ba8133"><img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social"></a>&nbsp;
    <a target="_blank" href="https://twitter.com/awesome_ama"><img src="https://img.shields.io/twitter/follow/awesome_ama?style=social"></a>
    <br>
</div>

<br>

# Dot product, Axis Operation and Broadcating - Day x of x

Hours completed : 1 hr 20mins <br>



# Resources used : 

- [Foundation- Numpy](https://madewithml.com/courses/foundations/numpy/)
<br>

Handwritten notes can be found [here][def]

[def]: https://github.com/barbaraaboagye/My-MachineLearning-Journey/blob/55efe34e3ae6057fdca704ffdd69321298b2372c/Handwritten%20notes/230322_DotProductAxisOperationAndBroadcast_NumpyFoundation.ipynb

### Dot product

The inside dimension of the matrix must match.

In [66]:
import numpy as np

In [67]:
# Dot product
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[9,10],[11,12]]) 
c = a.dot(b)

print(f"{a.shape} . {b.shape} = {c.shape}")
print(c)

(2, 3) . (3, 2) = (2, 2)
[[ 58  64]
 [139 154]]


The inner dimensions of `a` and `b` are the same, that is `3` so a dot product can be performeed. The results is a `2 x 2` matrix 

In [68]:
# When the inner dimensions are not the same. 
b = np.array([[1,2,3,4]])
print(a.shape)
print(b.shape)
# a.dot(b) An error message : ValueError: shapes (2,2) and (1,4) not aligned: 2 (dim 1) != 1 (dim 0)
a = np.array([[1,2],[3,4]])


(2, 3)
(1, 4)


### Axis operation

This is cool. It's possible to do operations across axis, i.e. sum all elements in the matric or sum only the rows or columns

In [69]:
# Sum across a dimension
x = np.array([[1,2],[3,4]])
print(x)
print ("sum all:", np.sum(x)) #add all elements in the matrix
print ("sum the comlumn(axis=0):",np.sum(x,axis =0)) # sum along rows
print ("sum the row(axis=1):",np.sum(x,axis =1)) # sum along column

[[1 2]
 [3 4]]
sum all: 10
sum the comlumn(axis=0): [4 6]
sum the row(axis=1): [3 7]


When `axis=0`, the operation is performed vertically, i.e., along the rows. For example, if you have a 2-dimensional array `arr` of shape (3, 4), `axis=0` means that the operation is performed on the 3 rows, resulting in a 1-dimensional array of length 4.

When `axis=1`, the operation is performed horizontally, i.e., along the columns. For example, if you have the same 2-dimensional array `arr` of shape (3, 4), `axis=1` means that the operation is performed on the 4 columns, resulting in a 1-dimensional array of length 3.

In [70]:
# Min/Max
x = np.array([[1,2,3],[4,5,6]])
print ("min:",x.min())
print ("max:",x.max())
print ('min axis =0 ',x.min(axis = 0)) #operation done vertically (along the columns)
print ('min axis =1 ',x.min(axis = 1)) #operation done horiazontally (along the rows)



min: 1
max: 6
min axis =0  [1 2 3]
min axis =1  [1 4]


### Broadcast

Broadcast allows operations to be performed for tensors with incompatible/different shape, i.e. their inner dimensions are different without the need of copying the data.

The basic idea of broadcasting is to perform operations between two arrays of different shapes by "stretching" one or both of the arrays to match the shape of the other, so that element-wise operations can be carried out.

Here's an example to illustrate how broadcasting works:

In [71]:
a = np.array([1, 2, 3]) # vector
b = 2  #scalar

# Multiply each element of 'a' by 'b'
c = a * b

print(c)  # Output: [2, 4, 6]


[2 4 6]


In this example, we have an array `a` of shape (3,) and a scalar `b`. We perform element-wise multiplication between `a` and `b` by simply writing `a * b`.

Broadcasting allows the scalar `b` to be "stretched" or broadcast to match the shape of `a`. In this case, the scalar `b` is "stretched" to an array of shape (3,), with each element having the same value as the original scalar. The multiplication operation is then performed element-wise between the two arrays `a` and `b` that now have the same shape. The result is an array `c` of shape (3,) with each element being the product of the corresponding elements in `a` and `b`.

Broadcasting can be used to perform operations between arrays of different shapes, as long as the dimensions of the arrays are compatible. The rules of broadcasting are:

- If the arrays have the same number of dimensions, but different shapes, NumPy will "stretch" the dimensions of the smaller array to match the larger array.

- If the arrays have different numbers of dimensions, NumPy will "stretch" the smaller array to match the larger array by adding dimensions of size 1 to its shape until the shapes of the two arrays match.

- If the arrays have different shapes and cannot be broadcast, NumPy will raise a ValueError.

Broadcasting is a very useful feature in NumPy that allows for efficient and concise code when working with arrays of different shapes.

In [72]:
# Another example of broadcasting - The scalar is broadcast across the vector so that they have compatible shapes.

x = np.array([1,2]) # vector
y = np.array(3) # scalar
z = x + y
print ("z:\n", z)


z:
 [4 5]


In [73]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=1)
c = a + b
b
b.shape
#a.shape
b.ndim
print (c)


[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


### Broadcasting problems

In the situation below, what is the value of c and what are its dimensions?


In [74]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=1)
c = a + b
print (c)

[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


Two NumPy arrays `a` and `b` are created, an arithmetic operation is performed on them.

The first line creates a NumPy array `a` with the values (3, 4, 5).

The second line uses the `np.expand_dims()` function to add a new axis to `a` along axis 1, resulting in a new array `b` with shape (3, 1).

Finally, the third line performs an element-wise addition between `a` and `b`. Since `b` has only one column, NumPy broadcasts it to match the shape of `a`, resulting in an array `c` with shape (3, 3) where each element of `a` is added to the corresponding element in `b`. 

If one is not looking to broadcast, it's importatnt to ensure the shape of `a` is the same as the shape of `b`. This is important to avoid unintentioan broadcasting behaviour. To solve this, the shape of a is reshaped

In [75]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=1)
a = a.reshape(-1, 1)
c = a + b
print ("c\n:",c)
print ("shape of a:",a.shape) # (3, 1)
print ("shape of b:", b.shape)
print ("shape of c:",c.shape) # (3, 1)



c
: [[ 6]
 [ 8]
 [10]]
shape of a: (3, 1)
shape of b: (3, 1)
shape of c: (3, 1)


The code `a.reshape(-1, 1)` is used to reshape the NumPy array `a` into a 2-dimensional array with one column and as many rows as needed, while maintaining the same total number of elements. The `-1` in the first argument of `reshape()` means that the number of rows will be automatically determined based on the size of the array and the size of the second dimension (in this case, one column).


The code first creates a NumPy array `a` with shape (3,) and values (3, 4, 5).

Then, the `np.expand_dims()` function is used to add a new axis to the array `a` at position 1, which results in the shape (3, 1) for the new array `b`. The new axis adds an extra dimension to the array, and it is useful for performing operations that require arrays with matching shapes.

The code then uses `a.reshape(-1, 1)` to reshape the original array `a` into a new array with shape (3, 1). This produces the same result as `b`, which means that `a` and `b` have the same shape and can be added element-wise.

Finally, the code performs element-wise addition between the arrays `a` and `b` using the `+` operator, and assigns the result to the new array `c`. Since both `a` and `b` have the same shape, the resulting array `c` will also have shape (3, 1).