<div align="center">
    <h1> My Machine Learning Journey</h1>
Civl Engineer · Researcher Youtuber · Machine Learning Engineer (The Goal)
    <br>
    Sharing and documenting my progress and journey as I learn machine learning
     <br>
</div>

<br>

<div align="center">
    <a target="_blank" href="https://github.com/barbaraaboagye/My-MachineLearning-Journey"><img src="https://img.shields.io/github/last-commit/barbaraaboagye/My-MachineLearning-Journey"></a>&nbsp;
      <a target="_blank" href="https://www.youtube.com/channel/UCEYKFq7ZEg81GYxpzNqYZ4)"><img src="https://img.shields.io/youtube/channel/subscribers/UCEYKFq7ZEg81GYxpzNqYZ4Q?style=social"></a>&nbsp;
    <a target="_blank" href="https://fr.linkedin.com/in/barbara-aboagye-233ba8133"><img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social"></a>&nbsp;
    <a target="_blank" href="https://twitter.com/awesome_ama"><img src="https://img.shields.io/twitter/follow/awesome_ama?style=social"></a>
    <br>
</div>

<br>

# Indexing and Arithmetic - Day x of x

Hours completed : 1 hour <br>


# Resources used : 

- [Foundation- Numpy](https://madewithml.com/courses/foundations/numpy/)
<br>

Handwritten notes can be found [here][def]

[def]: https://github.com/barbaraaboagye/My-MachineLearning-Journey/blob/22935dfb6f501cf161bf059921b1a2693c99ae80/Handwritten%20notes/230321_IndexingAndArithmetic_NumpyFoundation.pdf 

### Numpy
This package is used for performing numerical analysis

### Setup

Import the `numpy` package and set seed of reproducibility. This ensures that everytime a random number is generated, the same results are obtained

In [2]:
import numpy as np

In [3]:
## Generate random numbers and initialise the seed. 

np.random.seed(seed =1234)
print(np.random.rand(5)) # Output : [0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]
np.random.seed(seed =1234)
print(np.random.rand(5)) # Output : [0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]
[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]


### Mathematical objects in linear algebra - Basic

- Scalar (0D tensor) : a single value. Eg. 6
- Vector (1D tensor) : row or column of values. Eg : [1 2 3] - row vector, $[1 2 3]^T$ - column vector
- Matrix (2D tensor) : and array of rows and columnns of values with different sizes. 
- 3D  tensor         : arrays of rows and columns with 3 dimensions

Note : When np.array([]) is not used. Element is not considered to be an array. could be a list or tuple, etc

In [6]:
# Scalar
x = np.array(6)
print ("x:", x)
print("x ndim:",x.ndim) #number of dimensions
print ("x shape:", x.shape) #dimensions
print ("x size:", x.size) #size of elements
print ("x dtype:", x.dtype) #data type

x: 6
x ndim: 0
x shape: ()
x size: 1
x dtype: int64


In [7]:
# Vector
x = np.array([1.2, 2.2 ,3.3]) #vectors are in square brackets
print ("x:", x)
print("x ndim:",x.ndim) #number of dimensions
print ("x shape:", x.shape) #dimensions
print ("x size:", x.size) #size of elements
print ("x dtype:", x.dtype) #data type #float datatype

x: [1.2 2.2 3.3]
x ndim: 1
x shape: (3,)
x size: 3
x dtype: float64


In [11]:
# Matrix
x = np.array([[1,2],[3,4],[4,5]])

print ("x:\n", x)
print("x ndim:",x.ndim) #number of dimensions
print ("x shape:", x.shape) #dimensions = number of rows x number of columns
print ("x size:", x.size) #size of elements
print ("x dtype:", x.dtype) #data type #float datatype

x:
 [[1 2]
 [3 4]
 [4 5]]
x ndim: 2
x shape: (3, 2)
x size: 6
x dtype: int64


In [15]:
# 3-D tensor
x = np.array([[[1,2],[3,4],[4,5],[6,7],[7,8]]]) #number of square brackets determines the dimension
print ("x:\n", x)
print("x ndim:",x.ndim) #number of dimensions
print ("x shape:", x.shape) #dimensions = number of rows x number of columns
print ("x size:", x.size) #size of elements
print ("x dtype:", x.dtype) #data type #float datatype

x:
 [[[1 2]
  [3 4]
  [4 5]
  [6 7]
  [7 8]]]
x ndim: 3
x shape: (1, 5, 2)
x size: 10
x dtype: int64


Here, `x` is a 3-D array with dimensions, because the array is enclosed in three sets of square brackets which gives the shape `(1, 5, 2)`, indicating one block of five rows and two columns, and a total of 10 elements.  

Each element in the array corresponds to a single value in the block, which gives a total of 5*2=10 elements

In NumPy, the number of square brackets used to create an array can be used to determine its number of dimensions. Here's a summary of the number of square brackets used for creating arrays of different dimensions:

- Scalar: A scalar is represented by a 0-dimensional array, and it has no square brackets. For example, `x = np.array(3)` creates a scalar with the value 3.

- Vector: A vector is represented by a 1-dimensional array, and it has one set of square brackets. For example, `x = np.array([1, 2, 3])` creates a vector with three elements.

- Matrix: A matrix is represented by a 2-dimensional array, and it has two sets of square brackets. For example, `x = np.array([[1, 2], [3, 4]])` creates a matrix with two rows and two columns.

- Tensor: A tensor is represented by an array with more than two dimensions, and it has more than two sets of square brackets. For example, `x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])` creates a 3-dimensional tensor with two 2x2 matrices.

So, to summarize:

- Scalar: 0 sets of square brackets
- Vector: 1 set of square brackets
- Matrix: 2 sets of square brackets
- Tensor: more than 2 sets of square bracket

There are several inbuilt functions in numpy to allow for the easy creation of tensors

In [16]:
# Functions
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2))) # identity matrix
print ("np.random.random((2,2)):\n", np.random.random((2,2)))


np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.27259261 0.27646426]
 [0.80187218 0.95813935]]


## Indexing

Specific values can be extracted using indexing. Indices start with 0 and one can use negative indices as well where -1 is the last item

In [30]:
# Indexing
x = np.array([[1,2,3,4], [5,6,7,8] , [9,10,11,12]])
print (x)
x.shape
x[0:2,1:3] # last element mentioned is not included. Interested in elements in row 0 and 1 and column 1 and 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[2, 3],
       [6, 7]])

In [32]:
x = np.array([1,2,3])
print ("x:",x)
print("x[0] :",x[0])
x[0] = 0 # changing the value of x[0]
print ("x:",x)

x: [1 2 3]
x[0] : 1
x: [0 2 3]


In [33]:
# Slicing

x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1])
print ("x row 0: ", x[0, :])
print ("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [34]:
# Integer array indexing

print (x)
rows_to_get = np.array([0, 1, 2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
# Combine sequences above to get values to get
print ("indexed values: ", x[rows_to_get, cols_to_get]) # (0, 0), (1, 2), (2, 1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [35]:
# Boolean array indexing

x = np.array([[1, 2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)
print ("x[x > 2]:\n", x[x > 2])


x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


### Arithmetic


In [43]:
# Basic math

x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[1,2],[3,4]],dtype =np.float64)
print("x+y = \n", np.add(x,y))
print("x-y = \n", np.subtract(x,y))
print("x*y = \n", np.multiply(x,y))


x+y = 
 [[2. 4.]
 [6. 8.]]
x-y = 
 [[0. 0.]
 [0. 0.]]
x*y = 
 [[ 1.  4.]
 [ 9. 16.]]


12