<div align="center">
    <h1> My Machine Learning Journey</h1>
Civl Engineer · Researcher Youtuber · Machine Learning Engineer (The Goal)
    <br>
    Sharing and documenting my progress and journey as I learn machine learning
     <br>
</div>

<br>

<div align="center">
    <a target="_blank" href="https://github.com/barbaraaboagye/My-MachineLearning-Journey"><img src="https://img.shields.io/github/last-commit/barbaraaboagye/My-MachineLearning-Journey"></a>&nbsp;
      <a target="_blank" href="https://www.youtube.com/channel/UCEYKFq7ZEg81GYxpzNqYZ4)"><img src="https://img.shields.io/youtube/channel/subscribers/UCEYKFq7ZEg81GYxpzNqYZ4Q?style=social"></a>&nbsp;
    <a target="_blank" href="https://fr.linkedin.com/in/barbara-aboagye-233ba8133"><img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social"></a>&nbsp;
    <a target="_blank" href="https://twitter.com/awesome_ama"><img src="https://img.shields.io/twitter/follow/awesome_ama?style=social"></a>
    <br>
</div>

<br>

# Transpose, Reshape, Joining, Expanding and removing - Day x of x

Hours completed : 1 hour <br>

# Resources used : 

- [Foundation- Numpy](https://madewithml.com/courses/foundations/numpy/)
<br>

Handwritten notes can be found [here][def]

[def]: https://github.com/barbaraaboagye/My-MachineLearning-Journey/blob/59a91ab9c136e6d97e3e9564aad7b410bd7b8751/Handwritten%20notes/230323_TransposeReshapeJoinExpand_NumpyFoundation.pdf

In [27]:
import numpy as np

### Transpose

This allows us to change the dimension of the tensor from example an array of `3 x2`, will become `2 x3` when transposed. This is useful when the dot product has to be used. 

In [28]:
# Transposing

x = np.array([[1,2,3],[4,5,6]])
print (f"x:\n {x} \n shape of x: {x.shape}")
y = np.transpose(x)
print (f"y:\n {y} \n shape of y: {y.shape}")


x:
 [[1 2 3]
 [4 5 6]] 
 shape of x: (2, 3)
y:
 [[1 4]
 [2 5]
 [3 6]] 
 shape of y: (3, 2)


### Reshape

`Reshape` is a function used to change the shape of a NumPy array without changing its data.

The `reshape` function allows you to specify the new shape of the array by passing a tuple of integers as an argument. The tuple should specify the size of each dimension of the array, in the order in which they should appear in the new shape. The reshape tensor has the same number of values as the original tensor. One can also use `-1` on a dimension and NumPy will infer the dimension based on the input tensor.

Here's an example:

In [29]:
# Reshaping

# create a 2-dimensional array with 6 element
x = np.array([[1,2,3,4,5,6]])
print (x)
print ("x.shape: ", x.shape)

# reshape the array to a 2-dimensional array with 2 rows and 3 columns
y = np.reshape(x, (2, 3))
print ("y: \n", y)
print ("y.shape: ", y.shape)


z = np.reshape(x, (2, -1))
print ("z: \n", z)
print ("z.shape: ", z.shape)


[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


 `z` is created by reshaping `x` to a new shape of `(2, -1)`. The `-1` in this case means that the size of the second dimension is inferred based on the size of the first dimension and the total number of elements in the array. Since `x` has 6 elements and we want 2 rows in `z`, the second dimension is inferred to be 3. The resulting array `z` also has shape `(2, 3)`.

There are pitfalls of reshaping where the reshaped tensor is not what we are looking for.  Sometimes the tensor may have to be transposed before using. When unsure about reshaping, it's important to create a dummy example to cross check instead of blindly going by the tensor shape as this can lead to alot of issues as one progresses.

### Joining

Tensors or arrays can be joined using `concatenation` or `stacking`. `Stacking` and `concatenating` are two different ways of combining arrays or matrices.

`Concatenation` is the process of combining arrays or matrices along an existing axis. For example, if you have two arrays of shape `(3,4)` and you concatenate them along axis 0, you will get an array of shape `(6,4)`.

`Stacking`, on the other hand, is the process of joining arrays along a new axis. For example, if you have two arrays of shape `(3,4)` and you stack them along a new axis, you will get an array of shape `(2,3,4)`. This new axis is often called the stacking axis.

In summary, `concatenation` is used to combine arrays along an existing axis while `stacking` is used to join arrays along a new axis.

In [30]:
np.random.seed(1111)
x = np.random.random((2,3))
print (x)
print (x.shape)

[[0.0955492  0.9250037  0.34357342]
 [0.31047694 0.00200984 0.23559472]]
(2, 3)


In [31]:
## Concatenation
y = np.concatenate([x,x], axis = 0) # concat on a specified axis (vertically)
print(y)
print(y.shape)

[[0.0955492  0.9250037  0.34357342]
 [0.31047694 0.00200984 0.23559472]
 [0.0955492  0.9250037  0.34357342]
 [0.31047694 0.00200984 0.23559472]]
(4, 3)


In [32]:
# Stacking

z = np.stack([x,x], axis = 0) # stack on new axis
print (z)
print(z.shape)


[[[0.0955492  0.9250037  0.34357342]
  [0.31047694 0.00200984 0.23559472]]

 [[0.0955492  0.9250037  0.34357342]
  [0.31047694 0.00200984 0.23559472]]]
(2, 2, 3)


## Expanding/ Reducing

It's possible to add and remove dimensions from tensors. This is to allow compatibility of certain operations.

In [33]:
### Adding dimensions

x = np.array([[1,2,3],[4,5,6]])
print("x:\n",x)
print("x.shape: ", x.shape)
y = np.expand_dims(x,axis = 1) #add 1 dim
print ("y: \n",y)
print("y.shape: ", y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


The `np.expand_dims()` function to add an extra dimension to `x` along axis 1. This creates a new array `y` with shape (2,1,3), which has an extra dimension at index 1. The `np.expand_dims()` function takes two arguments: the input array and the axis along which to add the new dimension.

Notice that `y` has an extra set of brackets compared to `x`, indicating the extra dimension that was added. `y` is a 3D array that contains 2 sub-arrays, each of which contains a single row of data with 3 elements

In [34]:
## Remove dimension

# Removing dimensions
x = np.array([[[1,2,3]],[[4,5,6]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # squeeze dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)  # notice extra set of brackets are gone


x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
