<div align="center">
    <h1> My Machine Learning Journey</h1>
Civl Engineer · Researcher Youtuber · Machine Learning Engineer (The Goal)
    <br>
    Sharing and documenting my progress and journey as I learn machine learning
     <br>
</div>

<br>

<div align="center">
    <a target="_blank" href="https://github.com/barbaraaboagye/My-MachineLearning-Journey"><img src="https://img.shields.io/github/last-commit/barbaraaboagye/My-MachineLearning-Journey"></a>&nbsp;
      <a target="_blank" href="https://www.youtube.com/channel/UCEYKFq7ZEg81GYxpzNqYZ4)"><img src="https://img.shields.io/youtube/channel/subscribers/UCEYKFq7ZEg81GYxpzNqYZ4Q?style=social"></a>&nbsp;
    <a target="_blank" href="https://fr.linkedin.com/in/barbara-aboagye-233ba8133"><img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social"></a>&nbsp;
    <a target="_blank" href="https://twitter.com/awesome_ama"><img src="https://img.shields.io/twitter/follow/awesome_ama?style=social"></a>
    <br>
</div>

<br>

# Topic - Day x of x

Hours completed : 1 hour <br>

I went over last weeks lessons and started the basics of numpy

# Resources used : 

- [Foundation- Numpy](https://madewithml.com/courses/foundations/numpy/)
<br>

Handwritten notes can be found [here][def]

[def]: https://github.com/barbaraaboagye/My-MachineLearning-Journey/blob/2e5cb0bf0dd262ee28e85f0b6cdbc91441a57423/Handwritten%20notes/230320_SetupAndBasics_NumpyFoundation.pdf

### Numpy
This package is used for performing numerical analysis

### Setup

Import the `numpy` package and set seed of reproducibility. This ensures that everytime a randomm bumber is generated, the same results are obtained

In [1]:
import numpy as np

### Random numbers generation
When you generate random numbers using a computer program, the numbers are not truly random, but are instead generated using a deterministic algorithm. The example below has different random numbers for `a` and `b`. Whenever the code is run. The values of `a` and `b` keeps on changing. To solve this a seed can be defined


In [18]:
a = np.random.rand(5)
b = np.random.rand(5)
print ("a :", a)
print ("b :", b)


a : [0.26800864 0.24307673 0.7893055  0.37798441 0.79447948]
b : [0.86733103 0.79581463 0.91718092 0.27112277 0.76085495]


The algorithm is initialized with a starting value, known as the `seed`. By setting the `seed` to a fixed value, you can ensure that the sequence of random numbers generated is reproducible - i.e., if you run the same program with the same `seed`, you will get the same sequence of random numbers every time. The `seed` is a set of arbitrary numbers that the user defines. The `seed` should be intialised every time the random number generator is executed. In the case of np.random.seed(seed=1234) in the example belpw, the np.random.seed() function is a method provided by the NumPy library that sets the seed value for the NumPy random number generator. This means that any subsequent calls to NumPy's random number generator will produce the same sequence of random numbers as long as the seed is not changed.

For example, if you call np.random.rand(5) after setting the seed to 1234, you will get the same sequence of 5 random numbers every time you run the program:

In [19]:
## Generate random numbers and initialise the seed. 

np.random.seed(seed =1234)
print(np.random.rand(5)) # Output : [0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]
np.random.seed(seed =1234)
print(np.random.rand(5)) # Output : [0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]
[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]


[0.0955492  0.9250037  0.34357342 0.31047694 0.00200984]


### Mathematical objects in linear algebra - Basic

- Scalar (0D tensor) : a single value. Eg. 6
- Vector (1D tensor) : row or column of values. Eg : [1 2 3] - row vector, $[1 2 3]^T$ - column vector
- Matrix (2D tensor) : and array of rows and columnns of values with different sizes. 
- 3D  tensor         : arrays of rows and columns with 3 dimensions
