<div align="center">
    <h1> My Machine Learning Journey</h1>
Civil Engineer · Researcher Youtuber · Machine Learning Engineer (The Goal)
    <br>
    Sharing and documenting my progress and journey as I learn machine learning
     <br>
</div>

<br>

<div align="center">
    <a target="_blank" href="https://github.com/barbaraaboagye/My-MachineLearning-Journey"><img src="https://img.shields.io/github/last-commit/barbaraaboagye/My-MachineLearning-Journey"></a>&nbsp;
      <a target="_blank" href="https://www.youtube.com/channel/UCEYKFq7ZEg81GYxpzNqYZ4)"><img src="https://img.shields.io/youtube/channel/subscribers/UCEYKFq7ZEg81GYxpzNqYZ4Q?style=social"></a>&nbsp;
    <a target="_blank" href="https://fr.linkedin.com/in/barbara-aboagye-233ba8133"><img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social"></a>&nbsp;
    <a target="_blank" href="https://twitter.com/awesome_ama"><img src="https://img.shields.io/twitter/follow/awesome_ama?style=social"></a>
    <br>
</div>

<br>

# PyTorch Foundation - Day x of x

Hours completed : 1hr <br>


# Resources used : 

- [Foundation- PyTorch](https://madewithml.com/courses/foundations/pytorch/)
<br>

Handwritten notes can be found [here][def]

[def]: https://github.com/barbaraaboagye/My-MachineLearning-Journey/blob/f19bcd442db121a37f2c1a261f97796169860bc2/Handwritten%20notes/230402_PytorchFoundations.pdf

### Set up 

In [24]:
import numpy as np
import torch

In [25]:
SEED = 1234

In [26]:
# Set seed for reproducibility

np.random.seed(seed=SEED)
torch.manual_seed(SEED)

### Basics 

We'll first cover some basics with PyTorch such as creating tensors and converting from common data structures (lists, arrays, etc.) to tensors.

In [27]:
# Creating a random tensor

x = torch.randn(2,3) # normal distribution (rand(2,3) -> uniform distribution)
print (f"Type: {x.type()}")
print (f"Size: {x.shape}")
print (f"Values: \n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


This code creates a tensor `x` of size `(2,3)` filled with random values from a normal distribution with mean 0 and standard deviation 1 using PyTorch.

The tensor `x` has 2 rows and 3 columns

In [28]:
#Zeros and Ones tensor

x = torch.zeros(2, 3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [29]:
# List to Tensor

x = [1,2,3], [4,5,6 ] # normal list
print (x)
print(np.shape(x))
print(f"Type: {np.ndim(x)}")
y = torch.Tensor([[1,2,3], [4,5,6 ]])
print (f"Size: {y.shape}")
print(f"x:\n {y}")
z = torch.Tensor(x)
print (f"Size: {z.shape}")
print(f"x:\n {z}")

([1, 2, 3], [4, 5, 6])
(2, 3)
Type: 2
Size: torch.Size([2, 3])
x:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Size: torch.Size([2, 3])
x:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [30]:
## NumPy array to Tensor

x = torch.Tensor(np.random.rand(2,3))
print (f"Size: {x.shape}")
print(f"x:\n {x}")

Size: torch.Size([2, 3])
x:
 tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [31]:
# Changing tensor type 
x = torch.Tensor(3,4)
print(f"Type: {x.type()}")
print(x)
x = x.long()
print(f"Type: {x.type()}")
print(x)

Type: torch.FloatTensor
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Type: torch.LongTensor
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


### Long tensor 

In programming, we often work with numbers, like 1, 2, 3, etc. However, sometimes we need to work with really large numbers that are too big to be represented using the normal integer data type.

For example, imagine you have a dataset with billions of entries, and you need to index into it using unique identifiers that are assigned to each entry. In this case, you would need a data type that can represent really large integer values, and that's where LongTensor comes in.

In PyTorch, a LongTensor is a special type of data structure that can hold large integer values ranging from -9223372036854775808 to 9223372036854775807. You can think of it like a container that can store really big numbers.

You can create a LongTensor by either explicitly converting an existing tensor of a different data type using the .long() method or by directly initializing it using the torch.LongTensor() constructor. Once you have a LongTensor, you can use it for various mathematical operations, just like any other tensor in PyTorch.

#### Operations

In [32]:
# Addition

x = torch.randn(2,3)
y = torch.randn(2,3)
z = x + y
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0761, -0.6775, -0.3988],
        [ 3.0633, -0.1589,  0.3514]])


In [33]:
## Dot product

x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x,y)
print(f"Size : {z.shape}")
print(f"Values : \n {z}")

Size : torch.Size([2, 2])
Values : 
 tensor([[ 1.0796, -0.0759],
        [ 1.2746, -0.5134]])


The `torch.mm()` function is used to perform matrix multiplication between two tensors of size `(m,n)` and `(n,p)`, resulting in a tensor of size `(m,p)`. In other words, it multiplies each element of each row of the first tensor with each element of each column of the second tensor, and then sums the products to get the corresponding element of the resulting tensor.

In [34]:
# Transpose

x = torch.randn(2,3)
print(f"Size : {x.shape}")
print (f"Values : \n{x}")
y = torch.t(x)
print(f"Size: {y.shape}")
print(f"Values: \n{y}")

Size : torch.Size([2, 3])
Values : 
tensor([[ 0.8042, -0.1383,  0.3196],
        [-1.0187, -1.3147,  2.5228]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8042, -1.0187],
        [-0.1383, -1.3147],
        [ 0.3196,  2.5228]])


In [35]:
## Reshape 
x = torch.randn(2,3)
print(f"Values x:\n {x}")
z = x.view(3,2)
print(f"Size: {z.shape}")
print (f"Values z:\n{z}")

Values x:
 tensor([[ 0.4501,  0.2709, -0.8087],
        [-0.0217, -1.0413,  0.0702]])
Size: torch.Size([3, 2])
Values z:
tensor([[ 0.4501,  0.2709],
        [-0.8087, -0.0217],
        [-1.0413,  0.0702]])


This code reshapes the tensor `x` using the `.view()` method in PyTorch and assigns the resulting tensor to `z`.

The `.view()` method in PyTorch is used to reshape a tensor to a new shape while maintaining the total number of elements in the tensor. In this case, the tensor `x` has dimensions `(2,3)` and a total of 6 elements.

The `.view(3, 2)` method is used to reshape `x` into a tensor with dimensions `(3,2)` which also has a total of 6 elements. The resulting tensor `z` will have 3 rows and 2 columns.

Note that when reshaping a tensor, the order of the elements in memory is preserved. In other words, the elements are simply rearranged to form the new shape without any change in their values. If the new shape does not have the same number of elements as the original tensor, a runtime error will be raised.

In [36]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")


Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


When we reshape a tensor, we need to be careful. Reshaping can change the order of the elements in the tensor, which can cause problems if we're not expecting it. In the code above, we first create a three-dimensional tensor `x`. Then, we reshape it into a tensor a with dimensions `(3, 8)`. This flattens the tensor, so that all the elements are in a single row.

Next, we transpose the first two dimensions of `x` to get a tensor `b`. However, `b` is not contiguous, which means that its elements are not in a simple, ordered sequence in memory. This can cause issues later on.

Finally, we reshape `b` into a tensor c with dimensions `(2, 12)` using the .view() method. This could also cause issues, since the elements of b are not contiguous.

So, when we reshape tensors, we need to be careful and make sure we understand the order of the element

In [37]:
## Dimensional operations
x = torch.randn(2, 3)
print(f"Values: \n{x}")
y = torch.sum(x, dim=0) # add each row's value for every column
print(f"Values: \n{y}")
z = torch.sum(x, dim=1) # add each columns's value for every row
print(f"Values: \n{z}")


Values: 
tensor([[ 0.5797, -0.0599,  0.1816],
        [-0.6797, -0.2567, -1.8189]])
Values: 
tensor([-0.1000, -0.3166, -1.6373])
Values: 
tensor([ 0.7013, -2.7553])


### Indexing 


In [39]:
x = torch.randn(3,4)
print (f"x: \n{x}")
print (f"x[:1] : \n{x[:1]} ") # select first row
print (f"x[:1,1:3] \n {x[:1,1:3]} ")

x: 
tensor([[ 0.2111,  0.3372,  0.6638,  1.0397],
        [ 1.8434,  0.6588, -0.2349, -0.0306],
        [ 1.7462, -0.0722, -1.6794, -1.7010]])
x[:1] : 
tensor([[0.2111, 0.3372, 0.6638, 1.0397]]) 
x[:1,1:3] 
 tensor([[0.3372, 0.6638]]) 


The second print statement displays a slice of the tensor `x` using indexing. Specifically, it uses the slice notation `x[:1]` to select the first row of the tensor.

The syntax `x[:1, 1:3]` means "select the first row (`:1`) and columns 1 to 2 (`1:3`) of the tensor `x`". The resulting sub-tensor will have shape `(1, 2)`, since it has one row and two columns.